"""add stop_loss_pct to bot_state

Revision ID: 20cb50116c95
Revises: e437b998fd4e
Create Date: 2026-05-26 21:37:39.465951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cb50116c95'
down_revision: Union[str, Sequence[str], None] = 'e437b998fd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_state', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'stop_loss_pct',
                sa.Float(),
                nullable=False,
                server_default='0.30',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_state', schema=None) as batch_op:
        batch_op.drop_column('stop_loss_pct')

    # ### end Alembic commands ###
