"""add market_filters and polymarket_tree_cache

Revision ID: 237ecd5154b4
Revises: 53cec702c555
Create Date: 2026-05-22 23:11:20.283706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237ecd5154b4'
down_revision: Union[str, Sequence[str], None] = '53cec702c555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("level IN ('sport','league','event')", name='ck_filter_level_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'identifier', name='uq_filter_level_identifier')
    )
    op.create_table('polymarket_tree_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='polymarket_tree_cache_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polymarket_tree_cache')
    op.drop_table('market_filters')
    # ### end Alembic commands ###
