"""add wallet_config table

Revision ID: 53cec702c555
Revises: 7a861608a888
Create Date: 2026-05-22 22:59:14.531752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cec702c555'
down_revision: Union[str, Sequence[str], None] = '7a861608a888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('encrypted_private_key', sa.String(), nullable=False),
    sa.Column('encrypted_api_key', sa.String(), nullable=True),
    sa.Column('encrypted_api_secret', sa.String(), nullable=True),
    sa.Column('funder_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='wallet_config_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_config')
    # ### end Alembic commands ###
