"""add risk fields to bot_state

Revision ID: 8213f18583f5
Revises: 20cb50116c95
Create Date: 2026-05-26 23:14:48.258384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8213f18583f5'
down_revision: Union[str, Sequence[str], None] = '20cb50116c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_state', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'max_total_exposure_usd',
                sa.Float(),
                nullable=False,
                server_default='200.0',
            )
        )
        batch_op.add_column(sa.Column('last_pause_reason', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('last_paused_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_state', schema=None) as batch_op:
        batch_op.drop_column('last_paused_at')
        batch_op.drop_column('last_pause_reason')
        batch_op.drop_column('max_total_exposure_usd')

    # ### end Alembic commands ###
