"""add polymarket_tokens and decision_log

Revision ID: b440ab278050
Revises: bc38535ceabd
Create Date: 2026-05-23 20:31:56.009834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b440ab278050'
down_revision: Union[str, Sequence[str], None] = 'bc38535ceabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('polymarket_event_id', sa.String(length=64), nullable=False),
    sa.Column('polymarket_token_id', sa.String(length=128), nullable=True),
    sa.Column('pm_outcome', sa.String(length=128), nullable=True),
    sa.Column('outcome_side', sa.String(length=8), nullable=True),
    sa.Column('sport', sa.String(length=32), nullable=True),
    sa.Column('league', sa.String(length=128), nullable=True),
    sa.Column('pm_event_title', sa.String(length=512), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('fair_prob', sa.Float(), nullable=True),
    sa.Column('poly_best_bid', sa.Float(), nullable=True),
    sa.Column('poly_best_ask', sa.Float(), nullable=True),
    sa.Column('poly_ask_depth_usd', sa.Float(), nullable=True),
    sa.Column('pinnacle_decimal_odd', sa.Float(), nullable=True),
    sa.Column('pinnacle_raw_prob', sa.Float(), nullable=True),
    sa.Column('ev', sa.Float(), nullable=True),
    sa.Column('proposed_stake_usd', sa.Float(), nullable=True),
    sa.Column('proposed_price', sa.Float(), nullable=True),
    sa.Column('seconds_to_kickoff', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_log', schema=None) as batch_op:
        batch_op.create_index('idx_dlog_action', ['action', 'captured_at'], unique=False)
        batch_op.create_index('idx_dlog_event', ['polymarket_event_id'], unique=False)
        batch_op.create_index('idx_dlog_ts', ['captured_at'], unique=False)

    op.create_table('polymarket_tokens',
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('polymarket_event_id', sa.String(length=64), nullable=False),
    sa.Column('market_condition_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=128), nullable=False),
    sa.Column('outcome_side', sa.String(length=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('polymarket_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_pmtoken_event', ['polymarket_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polymarket_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_pmtoken_event')

    op.drop_table('polymarket_tokens')
    with op.batch_alter_table('decision_log', schema=None) as batch_op:
        batch_op.drop_index('idx_dlog_ts')
        batch_op.drop_index('idx_dlog_event')
        batch_op.drop_index('idx_dlog_action')

    op.drop_table('decision_log')
    # ### end Alembic commands ###
