"""add event_matches

Revision ID: bc38535ceabd
Revises: d60d7404b759
Create Date: 2026-05-23 13:02:44.581882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc38535ceabd'
down_revision: Union[str, Sequence[str], None] = 'd60d7404b759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('polymarket_event_id', sa.String(length=64), nullable=False),
    sa.Column('external_event_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('home_score', sa.Float(), nullable=False),
    sa.Column('away_score', sa.Float(), nullable=False),
    sa.Column('time_delta_minutes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polymarket_event_id', 'source', name='uq_match_polyev_source')
    )
    with op.batch_alter_table('event_matches', schema=None) as batch_op:
        batch_op.create_index('idx_match_extev', ['external_event_id'], unique=False)
        batch_op.create_index('idx_match_polyev', ['polymarket_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_matches', schema=None) as batch_op:
        batch_op.drop_index('idx_match_polyev')
        batch_op.drop_index('idx_match_extev')

    op.drop_table('event_matches')
    # ### end Alembic commands ###
