"""add odds_snapshots

Revision ID: ce68b1a98869
Revises: 237ecd5154b4
Create Date: 2026-05-22 23:21:29.199925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce68b1a98869'
down_revision: Union[str, Sequence[str], None] = '237ecd5154b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('market_condition_id', sa.String(length=128), nullable=True),
    sa.Column('token_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('mid_price', sa.Float(), nullable=True),
    sa.Column('bid_depth_usd', sa.Float(), nullable=True),
    sa.Column('ask_depth_usd', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_odds_event_time', ['event_id', 'captured_at'], unique=False)
        batch_op.create_index('idx_odds_token_time', ['token_id', 'captured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_odds_token_time')
        batch_op.drop_index('idx_odds_event_time')

    op.drop_table('odds_snapshots')
    # ### end Alembic commands ###
