"""add external_events

Revision ID: d60d7404b759
Revises: ce68b1a98869
Create Date: 2026-05-23 12:50:50.189737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60d7404b759'
down_revision: Union[str, Sequence[str], None] = 'ce68b1a98869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_event_id', sa.String(length=128), nullable=False),
    sa.Column('sport', sa.String(length=64), nullable=True),
    sa.Column('league', sa.String(length=128), nullable=True),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_event_id', name='uq_extev_source_id')
    )
    with op.batch_alter_table('external_events', schema=None) as batch_op:
        batch_op.create_index('idx_extev_source_start', ['source', 'start_time'], unique=False)
        batch_op.create_index('idx_extev_teams_start', ['home_team', 'away_team', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_events', schema=None) as batch_op:
        batch_op.drop_index('idx_extev_teams_start')
        batch_op.drop_index('idx_extev_source_start')

    op.drop_table('external_events')
    # ### end Alembic commands ###
