"""add bot_state orders positions

Revision ID: e437b998fd4e
Revises: b440ab278050
Create Date: 2026-05-24 03:18:33.957286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e437b998fd4e'
down_revision: Union[str, Sequence[str], None] = 'b440ab278050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('master_stake_usd', sa.Float(), nullable=False),
    sa.Column('ev_threshold', sa.Float(), nullable=False),
    sa.Column('exit_threshold', sa.Float(), nullable=False),
    sa.Column('max_concurrent_positions', sa.Integer(), nullable=False),
    sa.Column('max_daily_drawdown_usd', sa.Float(), nullable=False),
    sa.Column('min_time_to_game_minutes', sa.Integer(), nullable=False),
    sa.Column('max_time_to_game_minutes', sa.Integer(), nullable=False),
    sa.Column('min_ask_depth_usd', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='bot_state_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('polymarket_order_id', sa.String(length=128), nullable=True),
    sa.Column('polymarket_event_id', sa.String(length=64), nullable=True),
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.String(length=128), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('notional_usd', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('filled_size', sa.Float(), nullable=False),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polymarket_order_id', name='uq_orders_pm_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_orders_status_ts', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_orders_token', ['token_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('polymarket_event_id', sa.String(length=64), nullable=True),
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_at', sa.DateTime(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_at', sa.DateTime(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entry_order_id', sa.Integer(), nullable=True),
    sa.Column('exit_order_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('idx_positions_status', ['status'], unique=False)
        batch_op.create_index('idx_positions_token', ['token_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('idx_positions_token')
        batch_op.drop_index('idx_positions_status')

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_orders_token')
        batch_op.drop_index('idx_orders_status_ts')

    op.drop_table('orders')
    op.drop_table('bot_state')
    # ### end Alembic commands ###
