"""add exit_policy partial_state and indexes

Revision ID: fca6d243f89e
Revises: 8213f18583f5
Create Date: 2026-05-27 10:49:10.753981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca6d243f89e'
down_revision: Union[str, Sequence[str], None] = '8213f18583f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exit_policy', sa.String(length=8), nullable=True))

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'realized_pnl_partial_usd',
                sa.Float(),
                nullable=False,
                server_default='0.0',
            )
        )
        batch_op.create_index('idx_positions_exit_at', ['exit_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('idx_positions_exit_at')
        batch_op.drop_column('realized_pnl_partial_usd')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('exit_policy')

    # ### end Alembic commands ###
